#' Survey-calibrated distributional random forest (Algorithm 1)
#'
#' Trains the root-level PSU-honest SDRF described by Algorithm 1 of Zou,
#' Matabuena, and Kosorok. Split geometry is learned from design-weighted MMD
#' scores over a precomputed response RFF map. Leaves are populated only by the
#' PSU-disjoint estimation set, and predictions are Hajek-normalized weighted
#' distributions over the original multivariate responses.
#'
#' @param X Predictor matrix or data frame. Categorical data-frame columns are
#'   one-hot encoded in the same way as \code{drf}.
#' @param Y Numeric response matrix. Bivariate and higher-dimensional responses
#'   are supported.
#' @param pi First-order inclusion probabilities, one per row, in \code{(0,1]}.
#'   Pass probabilities, not already-inverted survey weights.
#' @param psu.id Primary sampling unit identifier per row. If NULL, each row is
#'   treated as its own PSU, appropriate only for an unclustered design.
#' @param strata.id Stratum identifier per row. It is used when generating
#'   convenience multipliers and combined with \code{psu.id} so PSU labels may
#'   repeat between strata.
#' @param resampling.multipliers Optional nonnegative \code{n x num.trees}
#'   matrix. Column \code{b} contains design-respecting \eqn{n^*_{b,i}}.
#'   For a complex or multistage design this should be generated by validated
#'   survey-bootstrap software and supplied explicitly.
#' @param multiplier.method Convenience generator used only when
#'   \code{resampling.multipliers} is NULL. \code{"external"} (the default)
#'   requires an explicit matrix; \code{"none"} uses all ones;
#'   \code{"poisson_unit"} uses independent mean-one Poisson unit weights;
#'   \code{"stratified_psu"} resamples whole PSUs with replacement separately
#'   by stratum. These options are not substitutes for an unidentified original
#'   multistage sampling design.
#' @param multiplier.averages Number of independently generated multiplier
#'   matrices averaged for each tree.
#' @param psu.resampling.probabilities Optional row-level PSU draw probabilities
#'   for \code{"stratified_psu"}; values must be constant within a PSU.
#' @param num.trees Number of trees \eqn{B}.
#' @param q Probability that an active PSU is assigned to the split set. Each
#'   PSU is drawn once; a finite-sample all-split draw raises an explicit error.
#' @param mtry Number of encoded predictor columns considered at each node. If
#'   NULL, defaults to \eqn{min(ceil(sqrt(p)) + 20, p)} after dummy encoding.
#' @param min.obs Minimum raw observation count in both children. If NULL,
#'   defaults to \eqn{max(20, ceil(sqrt(n)))}.
#' @param lambda.max Maximum allowed split-weight max/min ratio in each child.
#' @param max.depth Maximum tree depth, where zero means unlimited.
#' @param rff Optional \code{sdrf_rff} object or path to one. If NULL, it is
#'   computed for this training window.
#' @param num.rff, kernel, bandwidth, response.transform, rff.backend Arguments
#'   used when \code{rff} is NULL; see \code{sdrf_rff}.
#' @param num.threads Number of C++ tree-building threads. NULL uses hardware
#'   concurrency.
#' @param seed Integer seed for tree scheduling, PSU honesty, and convenience
#'   multiplier generation. RFF frequencies use \code{rff.seed}.
#' @param rff.seed Integer RFF frequency seed.
#'
#' @return An object of class \code{sdrf}. Use
#'   \code{predict(..., newdata=)} to obtain the conditional distribution as
#'   training-response weights or to evaluate a supported functional.
#' @export
sdrf <- function(X,
                 Y,
                 pi,
                 psu.id = NULL,
                 strata.id = NULL,
                 resampling.multipliers = NULL,
                 multiplier.method = c("external", "none", "poisson_unit", "stratified_psu"),
                 multiplier.averages = 1L,
                 psu.resampling.probabilities = NULL,
                 num.trees = 500L,
                 q = 0.5,
                 mtry = NULL,
                 min.obs = NULL,
                 lambda.max = NULL,
                 max.depth = 0L,
                 rff = NULL,
                 num.rff = 256L,
                 kernel = c("gaussian", "laplacian"),
                 bandwidth = NULL,
                 response.transform = c("scale", "none"),
                 rff.backend = c("auto", "cpu", "torch"),
                 num.threads = NULL,
                 seed = sample.int(.Machine$integer.max, 1L),
                 rff.seed = seed) {
  predictors <- prepare_sdrf_predictors(X)
  X.mat <- predictors$matrix
  if (is.null(mtry)) {
    mtry <- min(ceiling(sqrt(NCOL(X.mat)) + 20), NCOL(X.mat))
  }
  if (is.null(min.obs)) {
    min.obs <- max(20L, ceiling(sqrt(NROW(X.mat))))
  }

  if (is.vector(Y, mode = "numeric")) {
    Y <- matrix(Y, ncol = 1L)
  }
  validate_Y(Y, NROW(X.mat))
  Y <- as.matrix(Y)

  design <- validate_sdrf_design(pi, psu.id, strata.id, NROW(X.mat))
  multiplier.method <- match.arg(multiplier.method)
  validate_sdrf_scalar(num.trees, "num.trees", lower = 1, integer = TRUE)
  validate_sdrf_scalar(q, "q", lower = 0, upper = 1,
                       lower.open = TRUE, upper.open = TRUE)
  validate_sdrf_scalar(mtry, "mtry", lower = 1, upper = NCOL(X.mat),
                       integer = TRUE)
  validate_sdrf_scalar(min.obs, "min.obs", lower = 1, integer = TRUE)
  validate_sdrf_scalar(max.depth, "max.depth", lower = 0, integer = TRUE)
  validate_sdrf_scalar(seed, "seed", lower = 1,
                       upper = .Machine$integer.max, integer = TRUE)
  validate_sdrf_scalar(rff.seed, "rff.seed", lower = 0,
                       upper = .Machine$integer.max, integer = TRUE)

  if (is.null(lambda.max)) {
    baseline.weights <- 1 / design$pi
    lambda.max <- 5.5 * max(baseline.weights) / min(baseline.weights)
  }
  validate_sdrf_scalar(lambda.max, "lambda.max", lower = 1,
                       allow.infinite = TRUE)
  num.threads <- validate_num_threads(num.threads)

  if (is.null(resampling.multipliers)) {
    if (multiplier.method == "external") {
      stop(
        "Strict SDRF requires design-respecting resampling.multipliers. ",
        "Supply an n by num.trees matrix, or explicitly choose a documented ",
        "convenience multiplier.method."
      )
    }
    resampling.multipliers <- sdrf_multipliers(
      psu.id = design$psu.key,
      strata.id = design$strata.id,
      num.trees = num.trees,
      method = multiplier.method,
      averages = multiplier.averages,
      psu.probabilities = psu.resampling.probabilities,
      seed = seed
    )
  } else {
    multiplier.method <- "external"
  }
  resampling.multipliers <- validate_sdrf_multipliers(
    resampling.multipliers, NROW(X.mat), num.trees, design$psu.key
  )

  if (is.character(rff) && length(rff) == 1L) {
    rff <- readRDS(rff)
  }
  if (is.null(rff)) {
    rff <- sdrf_rff(
      Y = Y,
      num.rff = num.rff,
      kernel = match.arg(kernel),
      bandwidth = bandwidth,
      response.transform = response.transform,
      seed = rff.seed,
      backend = match.arg(rff.backend),
      num.threads = num.threads
    )
  }
  validate_sdrf_rff(rff, Y)

  data <- create_data_matrices(X.mat, outcome = Y)
  forest <- do.call.rcpp(
    sdrf_train,
    c(data, list(
      mtry = as.integer(mtry),
      num.trees = as.integer(num.trees),
      min.obs = as.integer(min.obs),
      q = q,
      lambda.max = lambda.max,
      max.depth = as.integer(max.depth),
      psu.ids = design$psu.key,
      inclusion.probabilities = design$pi,
      resampling.multipliers = resampling.multipliers,
      num.threads = num.threads,
      seed = as.integer(seed),
      rff.features = rff$features
    ))
  )

  # Do not add the legacy "drf" fallback class. An older installed package
  # must fail rather than silently ignore _leaf_sample_weights.
  class(forest) <- "sdrf"
  forest[["ci.group.size"]] <- 1L
  forest[["X.orig"]] <- X.mat
  forest[["is.df.X"]] <- predictors$is.data.frame
  forest[["Y.orig"]] <- Y
  forest[["sample.weights"]] <- NULL
  forest[["clusters"]] <- numeric(0)
  forest[["equalize.cluster.weights"]] <- FALSE
  forest[["mat.col.names"]] <- predictors$matrix.names
  forest[["mat.col.names.df"]] <- predictors$data.frame.names
  forest[["any.factor.or.character"]] <- predictors$has.categorical
  forest[["survey.pi"]] <- design$pi
  forest[["survey.psu.id"]] <- design$psu.id
  forest[["survey.strata.id"]] <- design$strata.id
  forest[["sdrf.q"]] <- q
  forest[["sdrf.min.obs"]] <- as.integer(min.obs)
  forest[["sdrf.lambda.max"]] <- lambda.max
  forest[["sdrf.max.depth"]] <- as.integer(max.depth)
  forest[["sdrf.multiplier.method"]] <- multiplier.method
  forest[["sdrf.multiplier.summary"]] <- list(
    dimensions = dim(resampling.multipliers),
    range = range(resampling.multipliers),
    column.mean.range = range(colMeans(resampling.multipliers))
  )
  rff.metadata <- rff
  rff.metadata$features <- NULL
  forest[["rff"]] <- rff.metadata
  forest[["tunable.params"]] <- list(
    q = q,
    mtry = mtry,
    min.obs = min.obs,
    lambda.max = lambda.max,
    max.depth = max.depth,
    kernel = rff$kernel,
    bandwidth = rff$bandwidth,
    num.rff = rff$num.rff
  )
  forest
}

#' Generate convenience SDRF resampling multipliers
#'
#' This helper covers simple experimental resampling schemes. For PPS,
#' calibration, finite-population corrections, or multistage SRSWOR designs,
#' generate replicate multipliers with design-specific survey software and pass
#' the resulting matrix to \code{sdrf} instead.
#'
#' @param psu.id PSU identifier per row.
#' @param strata.id Stratum identifier per row.
#' @param num.trees Number of multiplier columns.
#' @param method \code{"none"}, \code{"poisson_unit"}, or
#'   \code{"stratified_psu"}.
#' @param averages Number of independent draws averaged per column.
#' @param psu.probabilities Optional row-level probabilities for PSU draws.
#' @param seed Random seed.
#' @return A nonnegative numeric matrix with one row per observation and one
#'   column per tree.
#' @export
sdrf_multipliers <- function(psu.id,
                             strata.id = NULL,
                             num.trees,
                             method = c("none", "poisson_unit", "stratified_psu"),
                             averages = 1L,
                             psu.probabilities = NULL,
                             seed = 1L) {
  method <- match.arg(method)
  num.rows <- length(psu.id)
  if (is.null(strata.id)) {
    strata.id <- rep.int(1L, num.rows)
  }
  if (length(strata.id) != num.rows || anyNA(psu.id) || anyNA(strata.id)) {
    stop("psu.id and strata.id must be complete and have equal length.")
  }
  validate_sdrf_scalar(num.trees, "num.trees", lower = 1, integer = TRUE)
  validate_sdrf_scalar(averages, "averages", lower = 1, integer = TRUE)
  num.trees <- as.integer(num.trees)
  averages <- as.integer(averages)

  if (method == "none") {
    return(matrix(1, nrow = num.rows, ncol = num.trees))
  }

  set.seed(as.integer(seed))
  result <- matrix(0, nrow = num.rows, ncol = num.trees)
  if (method == "poisson_unit") {
    for (tree in seq_len(num.trees)) {
      for (draw in seq_len(averages)) {
        multiplier <- stats::rpois(num.rows, lambda = 1)
        while (all(multiplier == 0)) {
          multiplier <- stats::rpois(num.rows, lambda = 1)
        }
        result[, tree] <- result[, tree] + multiplier / averages
      }
    }
    return(result)
  }

  psu.key <- as.integer(interaction(strata.id, psu.id, drop = TRUE,
                                    lex.order = TRUE))
  if (!is.null(psu.probabilities)) {
    if (length(psu.probabilities) != num.rows ||
        anyNA(psu.probabilities) || any(psu.probabilities <= 0) ||
        any(!is.finite(psu.probabilities))) {
      stop("psu.probabilities must contain one positive finite value per row.")
    }
  }

  strata <- unique(strata.id)
  for (tree in seq_len(num.trees)) {
    for (draw in seq_len(averages)) {
      current <- numeric(num.rows)
      for (stratum in strata) {
        rows <- which(strata.id == stratum)
        psus <- unique(psu.key[rows])
        probabilities <- rep.int(1 / length(psus), length(psus))
        if (!is.null(psu.probabilities)) {
          probabilities <- vapply(psus, function(psu) {
            values <- unique(psu.probabilities[psu.key == psu])
            if (length(values) != 1L) {
              stop("psu.probabilities must be constant within each PSU.")
            }
            values
          }, numeric(1L))
          probabilities <- probabilities / sum(probabilities)
        }

        sampled.positions <- sample.int(
          length(psus), length(psus), replace = TRUE, prob = probabilities
        )
        sampled <- psus[sampled.positions]
        counts <- tabulate(match(sampled, psus), nbins = length(psus))
        # Dividing by m*p_k gives conditional expectation one even for
        # unequal PSU draw probabilities.
        psu.multiplier <- counts / (length(psus) * probabilities)
        current[rows] <- psu.multiplier[match(psu.key[rows], psus)]
      }
      result[, tree] <- result[, tree] + current / averages
    }
  }
  result
}

#' Estimate SDRF memory and artifact sizes
#'
#' Produces conservative byte estimates for one training window. Actual forest
#' size depends on pruning and serialization, while prediction weights are
#' normally sparse; the dense prediction value is an upper bound.
#'
#' @param n Number of training rows.
#' @param num.trees Number of trees.
#' @param num.rff Number of complex RFF coordinates.
#' @param q PSU split probability.
#' @param threads Concurrent C++ tree workers.
#' @param n.test Optional number of outer-sample prediction rows.
#' @return A data frame with byte and GiB estimates by component.
#' @export
sdrf_storage_estimate <- function(n,
                                  num.trees,
                                  num.rff,
                                  q = 0.5,
                                  threads = 1L,
                                  n.test = NULL) {
  validate_sdrf_scalar(n, "n", lower = 1, integer = TRUE)
  validate_sdrf_scalar(num.trees, "num.trees", lower = 1, integer = TRUE)
  validate_sdrf_scalar(num.rff, "num.rff", lower = 1, integer = TRUE)
  validate_sdrf_scalar(q, "q", lower = 0, upper = 1,
                       lower.open = TRUE, upper.open = TRUE)
  validate_sdrf_scalar(threads, "threads", lower = 1, integer = TRUE)
  if (!is.null(n.test)) {
    validate_sdrf_scalar(n.test, "n.test", lower = 1, integer = TRUE)
  }

  workers <- min(as.numeric(threads), as.numeric(num.trees))
  components <- c(
    rff.matrix = 16 * n * num.rff,
    multiplier.matrix = 8 * n * num.trees,
    multiplier.call.peak = 16 * n * num.trees,
    concurrent.tree.weights = 16 * n * workers,
    serialized.forest.approx = 16 * n * (1 - q) * num.trees
  )
  if (!is.null(n.test)) {
    components <- c(components, dense.prediction.upper = 8 * n * n.test)
  }
  data.frame(
    component = names(components),
    bytes = unname(components),
    GiB = unname(components) / 1024^3,
    row.names = NULL
  )
}

#' Predict from an SDRF object
#'
#' SDRF uses structural PSU honesty rather than ordinary OOB trees, so an
#' explicit outer-sample \code{newdata} matrix is required.
#'
#' @inheritParams predict.drf
#' @method predict sdrf
#' @export
predict.sdrf <- function(object,
                         newdata = NULL,
                         functional = NULL,
                         transformation = NULL,
                         custom.functional = NULL,
                         num.threads = NULL,
                         estimate.uncertainty = FALSE,
                         ...) {
  if (is.null(newdata)) {
    stop(
      "SDRF does not use ordinary OOB prediction; provide outer-sample newdata."
    )
  }
  if (isTRUE(estimate.uncertainty)) {
    stop(
      "CI-group uncertainty weights are not implemented for SDRF Algorithm 1."
    )
  }
  predict.drf(
    object = object,
    newdata = newdata,
    functional = functional,
    transformation = transformation,
    custom.functional = custom.functional,
    num.threads = num.threads,
    estimate.uncertainty = FALSE,
    ...
  )
}

#' @method print sdrf
#' @export
print.sdrf <- function(x, ...) {
  cat("Survey-calibrated distributional random forest (Algorithm 1)\n")
  cat("Number of trees:", x[["_num_trees"]], "\n")
  cat("Training observations:", NROW(x$X.orig), "\n")
  cat("PSUs:", length(unique(interaction(x$survey.strata.id,
                                          x$survey.psu.id))), "\n")
  cat("Kernel:", x$rff$kernel,
      "  bandwidth:", signif(x$rff$bandwidth, 5),
      "  RFFs:", x$rff$num.rff, "\n")
  cat("q:", x$sdrf.q,
      "  min.obs:", x$sdrf.min.obs,
      "  lambda.max:", signif(x$sdrf.lambda.max, 5), "\n")
  invisible(x)
}

prepare_sdrf_predictors <- function(X) {
  original.is.data.frame <- is.data.frame(X)
  if (is.vector(X, mode = "numeric") ||
      is.vector(X, mode = "character") || is.factor(X)) {
    X <- as.data.frame(X, row.names = names(X))
    original.is.data.frame <- TRUE
  }
  validate_X(X)

  if (is.data.frame(X)) {
    has.categorical <- any(vapply(
      X, function(column) is.factor(column) || is.character(column), logical(1L)
    ))
    X.mat <- if (has.categorical) {
      as.matrix(fastDummies::dummy_cols(X, remove_selected_columns = TRUE))
    } else {
      as.matrix(X)
    }
    matrix.names <- colnames(X.mat)
    data.frame.names <- names(X)
  } else {
    has.categorical <- FALSE
    X.mat <- X
    matrix.names <- NULL
    data.frame.names <- NULL
  }

  list(
    matrix = X.mat,
    is.data.frame = original.is.data.frame,
    has.categorical = has.categorical,
    matrix.names = matrix.names,
    data.frame.names = data.frame.names
  )
}

validate_sdrf_design <- function(pi, psu.id, strata.id, num.rows) {
  if (!is.numeric(pi) || length(pi) != num.rows || anyNA(pi) ||
      any(!is.finite(pi)) || any(pi <= 0 | pi > 1)) {
    stop("pi must contain one finite first-order probability in (0, 1] per row.")
  }
  if (is.null(psu.id)) {
    psu.id <- seq_len(num.rows)
  }
  if (is.null(strata.id)) {
    strata.id <- rep.int(1L, num.rows)
  }
  if (length(psu.id) != num.rows || length(strata.id) != num.rows ||
      anyNA(psu.id) || anyNA(strata.id)) {
    stop("psu.id and strata.id must be complete and have one value per row.")
  }
  psu.key <- as.integer(interaction(strata.id, psu.id, drop = TRUE,
                                    lex.order = TRUE))
  if (length(unique(psu.key)) < 2L) {
    stop("Algorithm 1 requires at least two PSUs in the training window.")
  }
  list(
    pi = as.numeric(pi),
    psu.id = psu.id,
    strata.id = strata.id,
    psu.key = psu.key
  )
}

validate_sdrf_rff <- function(rff, Y) {
  if (!inherits(rff, "sdrf_rff") || !is.matrix(rff$features) ||
      NROW(rff$features) != NROW(Y) || NCOL(rff$features) != 2L * rff$num.rff) {
    stop("rff must be an sdrf_rff object computed for this training window.")
  }
  expected <- response_fingerprint(Y)
  if (!identical(rff$response.fingerprint, expected)) {
    stop("The RFF response fingerprint does not match Y or its row order.")
  }
  invisible(rff)
}

validate_sdrf_multipliers <- function(multipliers,
                                      num.rows,
                                      num.trees,
                                      psu.key = NULL) {
  multipliers <- as.matrix(multipliers)
  if (!is.numeric(multipliers) ||
      !identical(dim(multipliers), c(as.integer(num.rows), as.integer(num.trees))) ||
      anyNA(multipliers) || any(!is.finite(multipliers)) ||
      any(multipliers < 0) || any(colSums(multipliers > 0) == 0)) {
    stop(
      "resampling.multipliers must be a finite nonnegative n by num.trees ",
      "matrix with a positive value in every column."
    )
  }
  if (!is.null(psu.key)) {
    active.psus <- vapply(seq_len(NCOL(multipliers)), function(tree) {
      length(unique(psu.key[multipliers[, tree] > 0]))
    }, integer(1L))
    invalid <- which(active.psus < 2L)
    if (length(invalid) > 0L) {
      shown <- paste(utils::head(invalid, 10L), collapse = ", ")
      stop(
        "Every multiplier column must activate at least two PSUs. Invalid ",
        "column(s): ", shown,
        if (length(invalid) > 10L) ", ..." else ""
      )
    }
  }
  multipliers
}

validate_sdrf_scalar <- function(value,
                                 name,
                                 lower = -Inf,
                                 upper = Inf,
                                 lower.open = FALSE,
                                 upper.open = FALSE,
                                 integer = FALSE,
                                 allow.infinite = FALSE) {
  finite.ok <- is.finite(value) || (allow.infinite && is.infinite(value) && value > 0)
  lower.ok <- if (lower.open) value > lower else value >= lower
  upper.ok <- if (upper.open) value < upper else value <= upper
  if (length(value) != 1L || !is.numeric(value) || is.na(value) ||
      !finite.ok || !lower.ok || !upper.ok ||
      (integer && value != floor(value))) {
    stop(name, " has an invalid value.")
  }
  invisible(value)
}